### ISSUE TITLE
how to generate meta data?

### ISSUE THREAD

**Issue by zzx0836** [cyang-cityu/MetaCorrection#4]
Dear author, 

It is a great work in UDA. However, I have a question. In this paper, what is meta data? and how to generate meta data? In your code I can't find how to generate meta data. please give me some advice.

**Comment by cyang-cityu** [comment]
Thanks for your interest in our work. The meta data is generated by applying a domain predictor on source data to obtain those target-like source pixels. The code is updated to obtain the meta data online.
